apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: 05-app-helm
  namespace: argocd
spec: 
  destination: 
    namespace: 05-app-helm
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: argocd/03-applications/05-app-helm/helm-demo
    repoURL: "git@github.com:nguyenan122/k8s-self-learn.git"
    targetRevision: HEAD
    helm:
     releaseName: my-release
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
