apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 07-app-in-app-geocentric-model
  namespace: argocd
spec:
  destination:
    namespace: 07-app-in-app-geocentric-model
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: argocd/03-applications/07-app-in-app/manifests/geocentric-model
    repoURL: "git@github.com:nguyenan122/k8s-self-learn.git"
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
